import * as tsToZod from 'ts-to-zod'
import * as vscode from 'vscode'

export async function genZod(文本: string): Promise<void> {
  var 转换结果 = tsToZod.generate({
    sourceText: 文本,
  })

  var 结果 = 转换结果.getZodSchemasFile('')
  结果 = 结果.replace('// Generated by ts-to-zod\nimport { z } from "zod";', '').trim()

  if (结果 == '') {
    vscode.window.showErrorMessage('转换失败')
    return
  }

  await vscode.env.clipboard.writeText(结果)
  vscode.window.showInformationMessage('zod描述已复制到剪切板')
}
